-- MySQL Script generated by MySQL Workbench
-- Fri Jul 17 11:45:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE db584027681;

-- -----------------------------------------------------
-- Table `extras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extras` ;

CREATE TABLE IF NOT EXISTS `extras` (
  `extra_id` INT NOT NULL AUTO_INCREMENT ,
  `user_id` INT NOT NULL ,
  `article_id` INT NOT NULL ,
  `description` VARCHAR(1000) NOT NULL ,
  `img` BLOB NULL ,
  `college` VARCHAR(50) NOT NULL ,
  `club_or_organization` VARCHAR(100) NOT NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  PRIMARY KEY (`extra_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(100) NOT NULL ,
  `college` VARCHAR(50) NOT NULL ,
  `username` VARCHAR(100) NOT NULL ,
  `email` VARCHAR(150) NOT NULL ,
  `password` VARCHAR(200) NOT NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  `remember_token` VARCHAR(100) NULL ,
  PRIMARY KEY (`user_id`)  );


-- -----------------------------------------------------
-- Table `events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `events` ;

CREATE TABLE IF NOT EXISTS `events` (
  `event_id` INT NOT NULL AUTO_INCREMENT ,
  `article_id` INT NOT NULL ,
  `location` VARCHAR(200) NULL ,
  `time1` DATETIME NOT NULL ,
  `time2` DATETIME NULL ,
  `title` VARCHAR(200) NOT NULL ,
  `url` VARCHAR(1000) NOT NULL ,
  `type` VARCHAR(100) NOT NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  PRIMARY KEY (`event_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ath`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ath` ;

CREATE TABLE IF NOT EXISTS `ath` (
  `ath_id` INT NOT NULL AUTO_INCREMENT ,
  `article_id` INT NOT NULL ,
  `speaker` VARCHAR(100) NOT NULL ,
  `description` VARCHAR(300) NOT NULL ,
  `event_time` TIME NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  PRIMARY KEY (`ath_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flex_hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flex_hours` ;

CREATE TABLE IF NOT EXISTS `flex_hours` (
  `flex_id` INT NOT NULL AUTO_INCREMENT ,
  `store_name` TIME NOT NULL ,
  `wk_m_o` TIME NOT NULL ,
  `wk_m_c` TIME NOT NULL ,
  `wk_l_o` TIME NOT NULL ,
  `wk_l_c` TIME NOT NULL ,
  `wk_d_o` TIME NOT NULL ,
  `wk_d_c` TIME NOT NULL ,
  `wkn_m_o` TIME NOT NULL ,
  `wkn_m_c` TIME NOT NULL ,
  `wkn_l_o` TIME NOT NULL ,
  `wkn_l_c` TIME NOT NULL ,
  `wkn_d_o` TIME NOT NULL ,
  `wkn_d_c` TIME NOT NULL ,
  PRIMARY KEY (`flex_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dining_hall_hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dining_hall_hours` ;

CREATE TABLE IF NOT EXISTS `dining_hall_hours` (
  `dhall_id` INT NOT NULL AUTO_INCREMENT ,
  `dining_hall_name` TIME NOT NULL ,
  `dining_hall_real` TIME NOT NULL ,
  `wk_b_o` TIME NOT NULL ,
  `wk_b_c` TIME NOT NULL ,
  `wk_l_o` TIME NOT NULL ,
  `wk_l_c` TIME NOT NULL ,
  `wk_d_o` TIME NOT NULL ,
  `wk_d_c` TIME NOT NULL ,
  `wk_br_o` TIME NOT NULL ,
  `wk_br_c` TIME NOT NULL ,
  `wk_wd_o` TIME NOT NULL ,
  `wk_wd_c` TIME NOT NULL ,
  PRIMARY KEY (`dhall_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snack` ;

CREATE TABLE IF NOT EXISTS `snack` (
  `snack_id` INT NOT NULL AUTO_INCREMENT ,
  `article_id` INT NOT NULL ,
  `foodname` VARCHAR(100) NOT NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  PRIMARY KEY (`snack_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sports` ;

CREATE TABLE IF NOT EXISTS `sports` (
  `sports_id` INT NOT NULL AUTO_INCREMENT ,
  `article_id` INT NOT NULL ,
  `college` VARCHAR(50) NOT NULL ,
  `team` VARCHAR(100) NOT NULL ,
  `opponent` VARCHAR(100) NOT NULL ,
  `location` VARCHAR(200) NULL ,
  `time_start` VARCHAR(50) NOT NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  `livestream` VARCHAR(20) NOT NULL ,
  PRIMARY KEY (`sports_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subscribers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subscribers` ;

CREATE TABLE IF NOT EXISTS `subscribers` (
  `subscriber_id` INT NOT NULL AUTO_INCREMENT ,
  `email` VARCHAR(150) NOT NULL ,
  `college` VARCHAR(50) NOT NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  PRIMARY KEY (`subscriber_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `email_articles` ;

CREATE TABLE IF NOT EXISTS `email_articles` (
  `article_id` INT NOT NULL AUTO_INCREMENT ,
  `post_date` DATE NOT NULL ,
  `file_directory` VARCHAR(500) NOT NULL ,
  `created_at` DATETIME NOT NULL ,
  `updated_at` DATETIME NOT NULL ,
  PRIMARY KEY (`article_id`)  ,
  UNIQUE INDEX `post_date_UNIQUE` (`post_date` ASC)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weather` ;

CREATE TABLE IF NOT EXISTS `weather` (
  `weather_id` INT NOT NULL AUTO_INCREMENT ,
  `article_id` INT NOT NULL ,
  `icon_today` VARCHAR(50) NOT NULL ,
  `morning_temp` INT(10) NOT NULL ,
  `day_max` INT(10) NOT NULL ,
  `day_min` INT(10) NOT NULL ,
  `next_day_max` INT(10) NOT NULL ,
  `next_day_min` INT(10) NOT NULL ,
  `icon_nextday` VARCHAR(50) NOT NULL ,
  `next_day2_max` INT(10) NOT NULL ,
  `next_day2_min` INT(10) NOT NULL ,
  `icon_day2` VARCHAR(50) NOT NULL ,
  `next_day3_max` INT(10) NOT NULL ,
  `next_day3_min` INT(10) NOT NULL ,
  `icon_day3` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`weather_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_keys` ;

CREATE TABLE IF NOT EXISTS `api_keys` (
  `api_id` INT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(100) NOT NULL ,
  `key` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`api_id`)  )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
